# Generated by Django 2.1.7 on 2019-03-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190328_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='avatar',
        ),
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(default='', upload_to='authors'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='logo',
            field=models.ImageField(default='', upload_to='publishers'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='', upload_to='books/'),
        ),
    ]
