# Generated by Django 2.1.7 on 2019-03-28 11:41

from django.db import migrations, models
from django.conf import settings
from django.contrib.auth import get_user_model


def set_my_default_author_creator(apps, schema_editor):
    Author = apps.get_model('api', 'Author')
    for author in Author.objects.all().iterator():
        author.creator = get_user_model.objects.get(pk=1)
        author.save()


def set_my_default_publisher_creator(apps, schema_editor):
    Publisher = apps.get_model('api', 'Publisher')
    for publisher in Publisher.objects.all().iterator():
        publisher.creator = get_user_model.objects.get(pk=1)
        publisher.save()


def set_my_default_book_creator(apps, schema_editor):
    Book = apps.get_model('api', 'Book')
    for book in Book.objects.all().iterator():
        book.creator = get_user_model.objects.get(pk=1)
        book.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190328_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='creator',
            field=models.ForeignKey(
                settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE,
                null=True,
            ),
        ),
        migrations.RunPython(set_my_default_author_creator),
        migrations.AlterField(
            model_name='author',
            name='creator',
            field=models.ForeignKey(
                settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE,
            ),
        ),
        migrations.AddField(
            model_name='publisher',
            name='creator',
            field=models.ForeignKey(
                settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE,
                null=True,
            ),
        ),
        migrations.RunPython(set_my_default_publisher_creator),
        migrations.AlterField(
            model_name='publisher',
            name='creator',
            field=models.ForeignKey(
                settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE,
            ),
        ),
        migrations.AddField(
            model_name='book',
            name='creator',
            field=models.ForeignKey(
                settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE,
                null=True,
            ),
        ),
        migrations.RunPython(set_my_default_book_creator),
        migrations.AlterField(
            model_name='book',
            name='creator',
            field=models.ForeignKey(
                settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE,
            ),
        ),
    ]
